use thiserror::Error;
use validator::ValidationErrors;

/// Custom error type for the operations related to data domains's objects.
///
/// # Description
///
/// - [DataDomainError::InvalidParams] is returned when a data object is built using wrong data for some of its
///   members. This is a wrapper and contains the error messages that could have been generated by the internal logic.
/// - [DataDomainError::InvalidId] is returned when an object is built using an ID that is badly formatted.
#[derive(Error, Debug)]
pub enum DataDomainError {
    #[error("Some params contain an invalid format")]
    InvalidParams {
        #[from]
        source: ValidationErrors,
    },
    #[error("The given Author ID hash an invalid format")]
    InvalidId,
    #[error("The given string is not a valid recipe's category")]
    InvalidRecipeCategory,
}
