name: Docker build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.REGISTRY_TOKEN }}
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/${{ github.repository }}
                labels: |
                  org.opencontainers.image.title=La Coctelera Backend
                  org.opencontainers.image.description=Backend Service
                tags: |
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
